[package]
name = "rust-tcpip"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = "0.1.40"
tracing-subscriber = {version = "0.3.20", feature = ["env-filter", "std","fmt"]}

thiserror = "2.0.17"
anyhow = "1.0.1"

tun-tap ="0.1.4"